const TYPE =  {
  
  CHANNEL_SET_ACTIVE        : "CHANNEL_SET_ACTIVE",
  SETTER_USER               : "SETTER_USER",
  CHANNEL_READ_MESSAGE      : "CHANNEL_READ_MESSAGE",
  SETTER_CONVERSATION       : "SETTER_CONVERSATION",
  FILTER_SORT_CONV          : "FILTER_SORT_CONV",
  SETTER_CONVERSATION_BACKUP: "SETTER_CONVERSATION_BACKUP"
}
export default TYPE;